config/routes.rb
Rails.application.routes.draw do

  resources :message_configs do
    resources :message_templates
    resources :template_strategies
    resources :message_datasources
  end

end

app/models/message_template.rb
class MessageTemplate < ActiveRecord::Base
  belongs_to :message_config
end

app/controllers/message_templates_controller.rb
class MessageTemplatesController < ApplicationController
  before_action :find_message_config
  before_action :set_message_template, only: [:show, :edit, :update, :destroy]

  # GET /message_templates
  # GET /message_templates.json
  def index
    @message_templates = @message_config.message_templates
  end

  # GET /message_templates/1
  # GET /message_templates/1.json
  def show
    if request.xhr?
      render '_show', layout: false;
    end
  end

  # GET /message_templates/new
  def new
    @message_template = @message_config.message_templates.new
    if request.xhr?
      render 'partials/_template_form', layout: false;
    end
  end

  # GET /message_templates/1/edit
  def edit
    if request.xhr?
      render 'partials/_template_form', layout: false;
    end
  end

  # POST /message_templates
  # POST /message_templates.json
  def create
    @message_template = @message_config.message_templates.new(message_template_params)

    respond_to do |format|
      if @message_template.save
        format.html { redirect_to message_config_message_template_url(@message_config, @message_template), notice: 'Message template was successfully created.' }
        format.json { render :show, status: :created, location: message_config_message_template_url(@message_config, @message_template) }
      else
        format.html { render :new }
        format.json { render json: @message_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /message_templates/1
  # PATCH/PUT /message_templates/1.json
  def update
    respond_to do |format|
      if @message_template.update(message_template_params)
        format.html { redirect_to message_config_message_template_url(@message_config, @message_template), notice: 'Message template was successfully updated.' }
        format.json { render :show, status: :ok, location: message_config_message_template_url(@message_config, @message_template) }
      else
        format.html { render :edit }
        format.json { render json: @message_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_templates/1
  # DELETE /message_templates/1.json
  def destroy
    @message_template.destroy
    respond_to do |format|
      format.html { redirect_to message_config_message_templates_url, notice: 'Message template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message_template
      @message_template = @message_config.message_templates.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_template_params
      params.require(:message_template).permit(:message_config_id, :name, :template)
    end

    def find_message_config()
      @message_config = find_resource_by_nested_path
    end
end

app/helpers/message_templates_helper.rb
module MessageTemplatesHelper
end

app/views/message_templates/_form.html.erb
<%= form_for([@message_config, @message_template], html:{class: 'form-horizontal'}) do |f| %>
  <% if @message_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message_template.errors.count, "error") %> prohibited this message_template from being saved:</h2>

      <ul>
      <% @message_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, class: 'control-label col-sm-3' %>
    <div class="col-sm-9">
    <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :template, class: 'control-label col-sm-3' %>
    <div class="col-sm-9">
      <%= f.text_area :template, :rows => 8, class: 'form-control' %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit '提交', class: 'btn btn-primary pull-right' %>
  </div>
<% end %>

app/views/message_templates/_show.html.erb
<div class="row box">
    <h2 class="title"><%= @message_template.name %></h2>
    <div class="col-xs-2">模板内容</div>
    <div class="col-xs-10"><%= @message_template.template %></div>
</div>

app/views/message_templates/_table.html.erb
<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Template</th>
        <th></th>
    </tr>
    </thead>

    <tbody>
    <% @message_templates.each do |message_template| %>
    <tr>
        <td><%= message_template.id %></td>
        <td><%= message_template.name %></td>
        <td><%= message_template.template %></td>
        <td>
            <%= link_to '查看', message_config_message_template_path(@message_config, message_template), class: 'btn btn-default btn-xs', data: {toggle: 'modal', target: '#globalModal'}  %>
            <%= link_to '编辑', edit_message_config_message_template_path(@message_config, message_template), class: 'btn btn-default btn-xs', data: {toggle: 'modal', target: '#globalModal'}  %>
            <%= link_to '删除', message_config_message_template_path(@message_config, message_template), method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure?', remote: true }  %>
        </td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/message_templates/edit.html.erb
<div class="row">
    <div class="box col-md-6">
        <h2 class="title">编辑消息模板</h2>
        <%= render 'form' %>
    </div>
</div>

<%= link_to '查看', message_config_message_template_path %> |
<%= link_to '返回', message_config_message_templates_path(@message_config) %>

app/views/message_templates/index.html.erb
<div class="row box">
    <h2 class="title">消息模板</h2>
    <%= render 'table' %>
    <%= link_to '新建消息模板', new_message_config_message_template_path(@message_config), class: 'btn btn-primary btn-sm' %>
</div>

app/views/message_templates/new.html.erb
<div class="row">
    <div class="box col-md-6">
        <h2 class="title">新建消息模板</h2>
        <%= render 'form' %>
    </div>
</div>
<%= link_to '返回', message_config_message_templates_path(@message_config) %>

app/views/message_templates/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'show' %>

<%= link_to 'Edit', edit_message_config_message_template_path %> |
<%= link_to 'Back', message_config_message_templates_path(@message_config) %>