config/routes.rb
Rails.application.routes.draw do

  resources :message_configs do
    resources :message_templates
    resources :template_strategies
    resources :message_datasources
  end

end

app/models/template_strategy.rb
class TemplateStrategy < ActiveRecord::Base
  belongs_to :message_config
end

app/controllers/template_strategies_controller.rb
class TemplateStrategiesController < ApplicationController
  before_action :find_message_config
  before_action :set_template_strategy, only: [:show, :edit, :update, :destroy]

  # GET /template_strategies
  # GET /template_strategies.json
  def index
    @template_strategies = @message_config.template_strategies
  end

  # GET /template_strategies/1
  # GET /template_strategies/1.json
  def show
    if request.xhr?
      render '_show', layout: false;
    end
  end

  # GET /template_strategies/new
  def new
    @template_strategy = @message_config.template_strategies.new
    if request.xhr?
      render 'partials/_strategy_form', layout: false;
    end
  end

  # GET /template_strategies/1/edit
  def edit
    if request.xhr?
      render 'partials/_strategy_form', layout: false;
    end
  end

  # POST /template_strategies
  # POST /template_strategies.json
  def create
    @template_strategy = @message_config.template_strategies.new(template_strategy_params)

    respond_to do |format|
      if @template_strategy.save
        format.html { redirect_to message_config_template_strategy_url(@message_config, @template_strategy), notice: 'Template strategy was successfully created.' }
        format.json { render :show, status: :created, location: message_config_template_strategy_url(@message_config, @template_strategy) }
      else
        format.html { render :new }
        format.json { render json: @template_strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /template_strategies/1
  # PATCH/PUT /template_strategies/1.json
  def update
    respond_to do |format|
      if @template_strategy.update(template_strategy_params)
        format.html { redirect_to message_config_template_strategy_url(@message_config, @template_strategy), notice: 'Template strategy was successfully updated.' }
        format.json { render :show, status: :ok, location: message_config_template_strategy_url(@message_config, @template_strategy) }
      else
        format.html { render :edit }
        format.json { render json: @template_strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /template_strategies/1
  # DELETE /template_strategies/1.json
  def destroy
    @template_strategy.destroy

    respond_to do |format|
      format.html { redirect_to message_config_template_strategies_url, notice: 'Template strategy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template_strategy
      @template_strategy = @message_config.template_strategies.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def template_strategy_params
      params.require(:template_strategy).permit(:message_config_id, :strategy_type, :language, :script)
    end

    def find_message_config()
      @message_config = find_resource_by_nested_path
    end
end

app/helpers/template_strategies_helper.rb
module TemplateStrategiesHelper
end

app/views/template_strategies/_form.html.erb
<%= form_for([@message_config, @template_strategy], html:{class: 'form-horizontal'}) do |f| %>
  <% if @template_strategy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template_strategy.errors.count, "error") %> prohibited this template_strategy from being saved:</h2>

      <ul>
      <% @template_strategy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :strategy_type, class: 'control-label col-sm-3' %>
    <div class="col-sm-9">
    <%= f.select :strategy_type, [['静态', 'static'], ['动态', 'dynamic']] ,class: 'form-control'%>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :language, class: 'control-label col-sm-3' %>
    <div class="col-sm-9">
    <%= f.select :language, ['json', 'groovy', 'config'], class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :script, class: 'control-label col-sm-3' %>
    <div class="col-sm-9">
    <%= f.text_area :script, class: 'form-control', rows: 8%>
    </div>
  </div>
  <div class="actions">
    <%= f.submit '提交', class: 'btn btn-primary pull-right' %>
  </div>
<% end %>

app/views/template_strategies/_show.html.erb
<div class="row box">
    <h2 class="title"><%= @message_config.name %></h2>
    <div class="col-xs-2">类型</div>
    <div class="col-xs-10"><%= @template_strategy.strategy_type %></div>
    <div class="col-xs-2">脚本类型</div>
    <div class="col-xs-10"><%= @template_strategy.language %></div>
    <div class="col-xs-2">脚本内容</div>
    <div class="col-xs-10"><%= @template_strategy.script %></div>
</div>

app/views/template_strategies/_table.html.erb
<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>ID</th>
        <th>类型</th>
        <th>语言</th>
        <th>Script</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @template_strategies.each do |template_strategy| %>
    <tr>
        <td><%= template_strategy.id %></td>
        <td><%= template_strategy.strategy_type %></td>
        <td><%= template_strategy.language %></td>
        <td><%= template_strategy.script %></td>
        <td>
            <%= link_to '查看', message_config_template_strategy_path(@message_config, template_strategy), class: 'btn btn-default btn-xs', data: {toggle: 'modal', target: '#globalModal'}  %>
            <%= link_to '编辑', edit_message_config_template_strategy_path(@message_config, template_strategy), class: 'btn btn-default btn-xs', data: {toggle: 'modal', target: '#globalModal'}  %>
            <%= link_to '删除', message_config_template_strategy_path(@message_config, template_strategy), method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure?', remote: true }  %>
        </td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/template_strategies/edit.html.erb
<div class="row">
    <div class="box col-md-6">
        <h2 class="title">编辑策略模板</h2>
        <%= render 'form' %>
    </div>
</div>
<%= link_to '查看', message_config_template_strategy_path(@message_config, @template_strategy) %> |
<%= link_to '返回', message_config_template_strategies_path %>

app/views/template_strategies/index.html.erb
<div class="row box">
    <h2 class="title">模板策略</h2>
    <%= render 'table' %>
    <%= link_to '新建模板策略', new_message_config_template_strategy_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/template_strategies/new.html.erb
<div class="row">
    <div class="box col-md-6">
        <h2 class="title">新建策略模板</h2>
        <%= render 'form' %>
    </div>
</div>

<%= link_to '返回', message_config_template_strategies_path %>

app/views/template_strategies/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'show' %>
<%= link_to 'Edit', edit_message_config_template_strategy_path(@message_config, @template_strategy) %> |
<%= link_to 'Back', message_config_template_strategies_path %>