config/routes.rb
Rails.application.routes.draw do

  resources :message_configs do
    resources :message_templates
    resources :template_strategies
    resources :message_datasources
  end

end

app/models/message_config.rb
class MessageConfig < ActiveRecord::Base
  has_many :message_templates
  has_many :template_strategies

end

app/controllers/message_configs_controller.rb
class MessageConfigsController < ApplicationController
  before_action :set_message_config, only: [:show, :edit, :update, :destroy]

  # GET /message_configs
  # GET /message_configs.json
  def index
    @message_configs = MessageConfig.all
  end

  # GET /message_configs/1
  # GET /message_configs/1.json
  def show
    @template_strategies = @message_config.template_strategies
    @message_templates = @message_config.message_templates
  end

  # GET /message_configs/new
  def new
    @message_config = MessageConfig.new
    if (request.xhr?)
      render 'partials/_config_form', layout: false;
    end
  end

  # GET /message_configs/1/edit
  def edit
    if (request.xhr?)
      render 'partials/_config_form', layout: false;
    end
  end

  # POST /message_configs
  # POST /message_configs.json
  def create
    @message_config = MessageConfig.new(message_config_params)

    respond_to do |format|
      if @message_config.save
        format.html { redirect_to @message_config, notice: 'Message config was successfully created.' }
        format.json { render :show, status: :created, location: @message_config }
      else
        format.html { render :new }
        format.json { render json: @message_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /message_configs/1
  # PATCH/PUT /message_configs/1.json
  def update
    respond_to do |format|
      if @message_config.update(message_config_params)
        format.html { redirect_to @message_config, notice: 'Message config was successfully updated.' }
        format.json { render :show, status: :ok, location: @message_config }
      else
        format.html { render :edit }
        format.json { render json: @message_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_configs/1
  # DELETE /message_configs/1.json
  def destroy
    @message_config.destroy
    respond_to do |format|
      format.html { redirect_to message_configs_url, notice: 'Message config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message_config
      @message_config = MessageConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_config_params
      params.require(:message_config).permit(:group, :biz_type, :name, :desc)
    end
end

app/helpers/message_configs_helper.rb
module MessageConfigsHelper
end

app/views/message_configs/_form.html.erb
<% @message_config ||= MessageConfig.new %>
<%= form_for(@message_config, remote: true, html:{class: 'form-horizontal'}) do |f| %>
  <% if @message_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message_config.errors.count, "error") %> prohibited this message_config from being saved:</h2>

      <ul>
      <% @message_config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :group, class: 'control-label col-sm-3'%>
    <div class="col-sm-9">
      <%= f.text_field :group, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :biz_type, class: 'control-label col-sm-3' %>
    <div class="col-sm-9">
      <%= f.text_field :biz_type, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :name, class: 'control-label col-sm-3' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :desc, class: 'control-label col-sm-3' %>
    <div class="col-sm-9">
      <%= f.text_area :desc, class: 'form-control', rows: 8 %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit '创建消息配置', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/message_configs/edit.html.erb
<div class="row">
    <div class="box col-md-6">
        <h2 class="title">编辑消息配置</h2>
        <%= render 'form' %>
    </div>
</div>
<%= link_to '查看', @message_config %> |
<%= link_to '后退', message_configs_path %>

app/views/message_configs/index.html.erb
<div class="row box">
    <h2 class="title">消息配置管理</h2>

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>Group</th>
            <th>Biz type</th>
            <th>Name</th>
            <th>Desc</th>
            <th colspan="4">操作</th>
        </tr>
        </thead>

        <tbody>
        <% @message_configs.each do |message_config| %>
        <tr>
            <td><%= link_to message_config.id, message_config %></td>
            <td><%= message_config.group %></td>
            <td><%= message_config.biz_type %></td>
            <td><%= message_config.name %></td>
            <td><%= message_config.desc %></td>
            <td>
                <%= link_to '编辑', edit_message_config_path(message_config), class: 'btn btn-default btn-xs', data: {toggle: 'modal', target: '#globalModal'}%>
                <%= link_to '删除', message_config_path(message_config, format: 'json'), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'btn btn-danger btn-xs' %>
                <%= link_to '创建新模板', new_message_config_message_template_path(message_config), class: 'btn btn-default btn-xs', data: {toggle: 'modal', target: '#globalModal'} %>
                <%= link_to '创建新策略', new_message_config_template_strategy_path(message_config), class: 'btn btn-default btn-xs', data: {toggle: 'modal', target: '#globalModal'} %>
            </td>
        </tr>
        <% end %>
        </tbody>
    </table>

    <%= link_to '新建消息配置', new_message_config_url, class: 'btn btn-primary btn-sm', data: {toggle: 'modal', target: '#globalModal'} %>
</div>

app/views/message_configs/new.html.erb
<div class="row">
    <div class="box col-md-6">
        <h2 class="title">新建消息配置</h2>
        <%= render 'form' %>
    </div>
</div>

<%= link_to '后退', message_configs_path %>

app/views/message_configs/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="nav nav-tabs">
    <li class="active"><a href="#current" data-toggle="tab">基本信息</a></li>
    <li><a href="#strategies" data-toggle="tab">模板策略</a></li>
    <li><a href="#templates" data-toggle="tab">消息模板</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="current">
        <br />
        <div class="row box">
            <h2 class="title"><%= @message_config.name %></h2>
            <div class="col-xs-2">名称</div>
            <div class="col-xs-10"><%= @message_config.name %></div>
            <div class="col-xs-2">分组</div>
            <div class="col-xs-10"><%= @message_config.group %></div>
            <div class="col-xs-2">业务类型</div>
            <div class="col-xs-10"><%= @message_config.biz_type %></div>
            <div class="col-xs-2">描述</div>
            <div class="col-xs-10"><%= @message_config.desc %></div>
        </div>
    </div>
    <div class="tab-pane" id="strategies">
        <br />
        <div class="row box">
            <h2 class="title">
                模板策略管理
                <%= link_to '新建', new_message_config_template_strategy_path(@message_config), class: 'btn btn-primary btn-xs pull-right', data: {toggle: 'modal', target: '#globalModal'}  %>
            </h2>
            <%= render template: 'template_strategies/_table' %>
        </div>
    </div>
    <div class="tab-pane" id="templates">
        <br />
        <div class="row box">
            <h2 class="title">
                消息模板管理
                <%= link_to '新建', new_message_config_message_template_path(@message_config), class: 'btn btn-primary btn-xs pull-right', data: {toggle: 'modal', target: '#globalModal'}  %>
            </h2>
            <%= render template: 'message_templates/_table' %>
        </div>
    </div>
</div>